# Generated by Django 3.1.6 on 2021-07-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ownername', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('moneys', models.IntegerField()),
                ('productsInBucket', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField()),
                ('name', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
