# Generated by Django 3.2.5 on 2021-07-20 11:09

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='moneys',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='productsInBucket',
            field=models.JSONField(default=shop.models.productsInBucketDefault, verbose_name='productsInBucket'),
        ),
    ]
