# Generated by Django 3.2.5 on 2021-07-21 05:35

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210720_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='productsInBucket',
            field=models.JSONField(default=shop.models.productsInBucketDefault),
        ),
    ]
