# Generated by Django 3.2.5 on 2021-07-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_myuser_productsinbucket'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProductInner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
