# Generated by Django 3.1.6 on 2021-07-21 08:48

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_myproductinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='productsInBucket',
            field=models.JSONField(default=shop.models.productsInBucketDefault, verbose_name='productsInBucket'),
        ),
    ]
